"""
Fairness and Bias Audit models.
Protected attributes are audited strictly outside the matching pipeline.
"""
from dataclasses import dataclass, field
from typing import Dict, Any, List, Optional


@dataclass
class GroupStats:
    """
    Subgroup distribution and selection statistics.
    """
    group_value: str
    sample_size: int
    selected_count: int
    selection_rate: float
    mean_score: float

    def to_dict(self) -> Dict[str, Any]:
        return {
            "group_value": self.group_value,
            "sample_size": self.sample_size,
            "selected_count": self.selected_count,
            "selection_rate": round(self.selection_rate, 4),
            "mean_score": round(self.mean_score, 4),
        }


@dataclass
class AuditMetric:
    """
    Detailed audit outcome for a single protected attribute.
    """
    protected_attribute: str
    privileged_group: str
    unprivileged_group: str
    disparate_impact_ratio: Optional[float]
    demographic_parity_diff: float
    four_fifths_compliant: bool
    is_statistically_valid: bool
    group_statistics: Dict[str, GroupStats] = field(default_factory=dict)
    notes: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "protected_attribute": self.protected_attribute,
            "privileged_group": self.privileged_group,
            "unprivileged_group": self.unprivileged_group,
            "disparate_impact_ratio": round(self.disparate_impact_ratio, 4) if self.disparate_impact_ratio is not None else None,
            "demographic_parity_diff": round(self.demographic_parity_diff, 4),
            "four_fifths_compliant": self.four_fifths_compliant,
            "is_statistically_valid": self.is_statistically_valid,
            "group_statistics": {k: v.to_dict() for k, v in self.group_statistics.items()},
            "notes": self.notes,
        }


@dataclass
class FairnessAuditReport:
    """
    Full fairness audit report generated by Pipeline 6.
    Output: audit metrics, sample size, potential disparities, warnings, limitations.
    """
    total_candidates: int
    selection_threshold: float
    metrics: List[AuditMetric] = field(default_factory=list)
    sample_size_by_group: Dict[str, Dict[str, int]] = field(default_factory=dict)
    potential_disparities: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    limitations: List[str] = field(default_factory=list)
    is_audit_passed: bool = True

    def to_dict(self) -> Dict[str, Any]:
        return {
            "total_candidates": self.total_candidates,
            "selection_threshold": self.selection_threshold,
            "is_audit_passed": self.is_audit_passed,
            "sample_size_by_group": self.sample_size_by_group,
            "metrics": [m.to_dict() for m in self.metrics],
            "potential_disparities": self.potential_disparities,
            "warnings": self.warnings,
            "limitations": self.limitations,
        }
