"""
Team Solver models and structures.
"""
from dataclasses import dataclass, field
from typing import Dict, Any, List
from veriskill.models.student import StudentProfile
from veriskill.models.skill import RequiredSkill


@dataclass
class MemberContribution:
    """
    Shows which skills a specific team member covers and key evidence.
    """
    student_id: str
    student_name: str
    covered_skills: List[str] = field(default_factory=list)
    key_evidence_highlights: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "student_id": self.student_id,
            "student_name": self.student_name,
            "covered_skills": self.covered_skills,
            "key_evidence_highlights": self.key_evidence_highlights,
        }


@dataclass
class TeamResult:
    """
    Optimal team generated by Pipeline 5.
    Output:
    team members, skill coverage, uncovered skills, reason for selection
    """
    team_members: List[StudentProfile] = field(default_factory=list)
    skill_coverage: float = 0.0  # 0.0 to 1.0
    covered_skills: List[str] = field(default_factory=list)
    uncovered_skills: List[str] = field(default_factory=list)
    member_contributions: List[MemberContribution] = field(default_factory=list)
    complementarity_score: float = 0.0
    selection_rationale: str = ""

    @property
    def team_size(self) -> int:
        return len(self.team_members)

    @property
    def skill_coverage_percentage(self) -> int:
        return int(round(self.skill_coverage * 100))

    def to_dict(self) -> Dict[str, Any]:
        return {
            "team_members": [
                {
                    "id": m.id,
                    "name": m.name,
                    "verified_skills": [s.normalized_skill for s in m.get_verified_skills()],
                }
                for m in self.team_members
            ],
            "team_size": self.team_size,
            "skill_coverage": round(self.skill_coverage, 4),
            "skill_coverage_percentage": self.skill_coverage_percentage,
            "covered_skills": self.covered_skills,
            "uncovered_skills": self.uncovered_skills,
            "member_contributions": [c.to_dict() for c in self.member_contributions],
            "complementarity_score": round(self.complementarity_score, 4),
            "selection_rationale": self.selection_rationale,
        }
